config/routes.rb
MakeMyNews::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => "registrations"}

  resources :news do
    member do
      get :like
    end

  end

  root :to => "home#index"

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  include LiveNews
  before_filter :authenticate_user!, :except => [:index, :show]

  def new
   @news = PublishNews.new
  end

  def create
    unless(params[:publish_news][:youtube_url].blank?)
      youtube_params = params[:publish_news][:youtube_url].split("?")[1]
      youtube_params = CGI::parse(youtube_params)
      params[:publish_news][:youtube_url] = youtube_params["v"][0]
    end
    puts "#{params[:publish_news][:youtube_url].inspect}-----------------------"
    respond_to do |format|
      if PublishNews.create!(params[:publish_news].merge!(:is_live => 1))
        format.html { redirect_to news_index_path(), notice: "Your News is created, we'll post your news once our admin verify content"  }
      else
        format.html { render action: "new", notice: 'Something went wrong.'  }
      end
    end
  end

  def index
      @news = PublishNews.all
      
     aajtak = "http://aajtak.intoday.in.feedsportal.com/c/34152/f/618432/index.rss?option=com_rss&feed=RSS1.0&no_html=1&rsspage=home"
     ndtv = "http://www.ndtv.com/video/player/news/video-story/237589"
     aajtak_vedio = "http://aajtak.intoday.in/index.php?option=com_rss&feed=RSS1.0&no_html=1&rsspage=video"
     toi = "http://dynamic.feedsportal.com/pf/555218/http://toi.timesofindia.indiatimes.com/rssfeedstopstories.cms"
     vd = "http://www.ndtv.com/video/player/news/my-son-is-not-a-terrorist-abu-hamzas-mother/237585"
     ibn_image = "http://ibnlive.in.com.feedsportal.com/c/33219/fe.ed/ibnlive.in.com/ibnrss/top.xml"
     begin
       #@latest_blog_posts = RSS::Parser.parse(open(ibn_image).read, false).items #[0...5]
       #@latest_blog_posts = LiveNews.new(ibn_image)
       #@latest_blog_posts = LiveNews.new #(ibn_image)
       puts "----------------------------------------#{@latest_blog_posts.inspect}"
     #rescue
       # Do nothing, just continue.  The view will skip the blog section if the feed is nil.
     #  @latest_blog_posts = nil
     end
  end

  def show
    @news = PublishNews.find(params[:id])
  end

  def news_pasre(path)
    return RSS::Parser.parse(open(ibn_image).read, false).items
  end

  #like a news
  def like
    news_id = PublishNews.find_by_id(params[:id].to_i)
    #check if user s logged in or a news id is a valid news
    if(!signed_in? || news_id.nil?)
      render :text => false
      return
    end
    if UserLikeNews.where(:user_id => current_user.id, :publish_news_id => news_id.id).empty?
      UserLikeNews.create!(:user_id => current_user.id, :publish_news_id => news_id.id)
    end
    render :text => true
    return
  end

end
=begin

<div class="news" style="min-height: 600px; border: 1px solid red;">


  <h1>Simple Blog Feed</h1>
  <% unless @latest_blog_posts.nil? %>
    The latest <%= pluralize(@latest_blog_posts.count, "post") %> from the blog.
    <ul>
      <% @latest_blog_posts.each do |post| %>
        <% if nil != post && post.respond_to?(:pubDate) %>
          <li>
            <%= link_to post.title, post.link, :target => "_blank" %><br/>
            <%= post.description.html_safe %><br/>
            (<%= time_ago_in_words(post.pubDate) %> ago via blog feed)
          </li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <p>
      <em>No blog posts to show.</em>
    </p>
  <% end %>
</div>
=end

app/helpers/news_helper.rb
module NewsHelper
  def not_like_yet?(news)
    UserLikeNews.where(:user_id => current_user.id, :publish_news_id => news).empty?
  end

end

app/views/news/index.html.erb
<div style="background-image:url(/assets/web/line.jpg); background-repeat:repeat-x; height:1px; width:943px;"></div>
<div class="middle-container">


	 <div class="left_box_4">
	 <br/>
	   <img alt="" src="/assets/web/latest-o.jpg" />
	  <img alt="" src="/assets/web/top10.jpg"/>
	  <img alt="" src="/assets/web/sports.jpg"/>
	  <img alt="" src="/assets/web/Entertainment.jpg"/>

          <ul class="aro">
          <%@news.each do |news|%>
            <li><%= link_to news.headline, news_path(news) %></li>
          <%end%>
	  </ul>
	  </div>

          <% if(!signed_in?) %>
	  <div class="left_box_2 h1">
            <%= render :partial => 'sessions/login' %>
	  </div>
          <%end%>
	  <div>
	  <div style="clear:both;"></div>

          

	 </div>
	 <div style="clear:both;"></div>
</div>
<div style="background-image:url(/assets/web/line.jpg); background-repeat:repeat-x; height:1px; width:943px; padding-bottom:20px;"></div>

app/views/news/new.html.erb
<div style="background-image:url(/assets/web/line.jpg); background-repeat:repeat-x; height:1px; width:943px;"></div>
<div class="middle-container">
  <div class="left_box_4">
    <br/>
    <h2><b>Publish News</b></h2>

    <%= simple_form_for @news, :url => "/news", :html => {:class => "forms", :multipart => true }  do |f| %>
      <error></error>

      <div class="input_left_ex">Headline:</div>
      <div class="input_right_ex">
        <%= f.input :headline, :label => false%>
      </div>
      <div class="clear-both"></div>

      <div class="input_left_ex">Category:</div>
      <div class="input_right_ex">
        <%= f.association :category, :label => false, :wrapper_html => {:class => "first"} %>
      </div>
      <div class="clear-both"></div>

      <div class="input_left_ex">Summary:</div>
      <div class="input_right_ex">
        <%= f.input :summary, :label => false, :as => :text, :input_html => { :cols => 50, :rows => 8 }%>
      </div>
      <div class="clear-both"></div>

      <div class="radio_options">
        <input type="radio" name="mltimedia_content" checked="checked" class="select_photo mltimedia_content" id="select_photo"/><label for="select_photo" class="select_photo">I have Photo to upload</label>
        <input type="radio" name="mltimedia_content" class="select_youtube mltimedia_content" id="select_youtube"/><label for="select_youtube" class="select_youtube">I have YouTube URL</label>
        <input type="radio" name="mltimedia_content" class="select_embed_vedio mltimedia_content" id="select_embed_vedio"/><label for="select_embed_vedio" class="select_embed_vedio">I have embed Video</label>
        
      </div>
      <div class="clear-both"></div>

      <div class="multimedia_photo">
        <div class="input_left_ex">Photo:</div>
        <div class="input file">
          <input type="file" name="publish_news[news_pic]" id="publish_news_news_pic" class="file" />
        </div>
        <div class="clear-both"></div>
      </div>


      <div class="multimedia_embedded_video" style="display:none">
        <div class="input_left_ex">Embed video:</div>
        <div class="input_right_ex">
          <%= f.input :embedded_video, :label => false, :as => :text, :input_html => { :cols => 50, :rows => 5 }%>
        </div>
        <div class="clear-both"></div>
      </div>

      <div class="multimedia_youtube" style="display:none">
        <div class="input_left_ex">Youtube URL:</div>
        <div class="input_right_ex">
          <%= f.input :youtube_url, :label => false, :input_html => {:style => "height:28px;"}%>
        </div>
        <div class="clear-both"></div>
      </div>

      <input type="image" style="height:29px; width:84px; border:none; margin-left:180px;" src="/assets/web/review.jpg" name="button"/>
      &nbsp; &nbsp;
      <input type="image" style="height:29px; width:84px; border:none; margin-left:10px;" src="/assets/web/publish.jpg" name="button"/>

    <%end%>
  </div>

  <div class="left_box_2 h1"></div>
  <div>
    <div style="clear:both;"></div>
     <div style="background-image:url(/assets/web/line.jpg); background-repeat:repeat-x; height:1px; width:943px; margin-top:20px;"></div>
  </div>
  <div style="clear:both;"></div>
</div>


<script type="text/javascript">
  $("input.mltimedia_content").click(function(){
    $(".multimedia_photo").hide();
    $(".multimedia_youtube").hide();
    $(".multimedia_embedded_video").hide();
    
    if($(this).hasClass("select_photo")){
      $(".multimedia_photo").show();
    }else if($(this).hasClass("select_youtube")){
      $(".multimedia_youtube").show();
    }else{
      $(".multimedia_embedded_video").show();
    }
    //return false;
  })
</script>

app/views/news/show.html.erb
<div style="background-image:url(/assets/web/line.jpg); background-repeat:repeat-x; height:1px; width:943px;"></div>
<div class="middle-container">

  <br/>
  <h2><%=@news.headline%></h2><br />

  
    <% if @news.news_pic.exists? then %>
      <div class="news_pic"><%= image_tag @news.news_pic.url(:small) %></div>
    <%elsif !@news.youtube_url.blank?%>
      <div class="news_pic" style="height:315px;width:560px">
        <iframe width="560" height="315" src="http://www.youtube.com/embed/<%=@news.youtube_url%>" frameborder="0" allowfullscreen></iframe>
      </div>
    <%elsif !@news.embedded_video.blank?%>
      <div class="news_pic" style="height:315px;width:560px">
        <%= raw @news.embedded_video%>
      </div>
    <% end %>
  
  <div class="news_summary">
    <%=@news.summary %>
  </div>

  <br />


  <% if(!signed_in?) %>
    <div class="left_box_2 h1" id="sign_in_box" style="display:none;">
      <%= render :partial => 'sessions/login' %>
    </div>
    <div class="right_box_2">
      <%= link_to "Like", "#", :onclick => "$('#sign_in_box').show();$('#user_email').focus();return false;"%>
    </div>
  <%else%>
    <%if not_like_yet?(@news)%>
      <div class="right_box_2">
        <%= link_to "Like", "#", :onclick => "return likeNews('#{like_news_path(@news)}', this);"%>
      </div>
    <%end%>
  <%end%>

 <!--
 <div style="clear:both; margin-bottom:10px;"></div>
 <div class="input_left">Comment:</div> <div class="input_right"><input name="" type="textarea" style="width:850px; line-height:40px" /></div>
 <div style="clear:both; margin-bottom:10px;"></div>
 <input name="button" type="image" src="images/post.jpg" style="height:29px; width:84px; border:none; margin-left:102px;"/>
 -->

</div>
<div style="background-image:url(/assets/web/line.jpg); background-repeat:repeat-x; height:1px; width:943px; padding-bottom:20px;"></div>