config/routes.rb
MakeMyNews::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => "registrations"}

  resources :news do
    member do
      get :like
    end

  end

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title>Make My news</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container_12">

      <div class="logo"><img src="/assets/web/logo.jpg" width="277" height="126" /></div>
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger"><%= alert.html_safe %></div>
      <% end %>

      <div id="navigation">
        <div class="session-secion">
          <% if(signed_in?) %>
            <%= render :partial => 'sessions/logout' %>
          <%end%>
        </div>
        
        <ul>
          <li>
            <%= link_to "Home", "/", :class => ("active" if params[:controller] == "home")%>
            <%= link_to "Post News", (signed_in? ? new_news_path() : "#sign_in"), :class => ("active" if params[:controller] == "news")%>
            <%= link_to "News", news_index_path(), :class => ("active" if params[:controller] == "news") %>
            <!--<a href="abt_us.html">Portfolio</a>-->
            <a href="contact_us.html">Contact</a>
          </li>
        </ul>
      </div>
<div style="clear:both;"></div>

<%= yield %>

<div style="clear:both;"></div>
    </div>

    <div class="footer">
      <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_preferred_1"></a>
        <a class="addthis_button_preferred_2"></a>
        <a class="addthis_button_preferred_3"></a>
        <a class="addthis_button_preferred_4"></a>
        <a class="addthis_button_compact"></a>
        <a class="addthis_counter addthis_bubble_style"></a>
      </div>

      <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f9ee5e830d5d31d"></script>
      <!-- AddThis Button END -->

      <div style="float:left;">© Copyright 2012 - make My News. All Rights are Reserved.</div>

      <div style="float:right;">Designed and developed by <a href="http://agileconsultancyservices.com/">ABS</a></div>

    </div>
    <!--
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-32365760-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    -->
    <!-- Place this tag where you want the +1 button to render -->
    <!--
    <g:plusone annotation="inline"></g:plusone>
    -->
    <!-- Place this render call where appropriate -->
    <!--
    <script type="text/javascript">
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    -->

  </body>
</html>